domain: d9beud.com
url: "https://d9beud.com"
baseurl: ""
title: "Vincent Bathelier"

markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
locale: fr_FR
twitter:
  username: d9beuD

social:
  github: https://github.com/d9beuD

description: |
  Après 5 ans d’études à EPSI Montpellier dont 3 en alternance, j’ai co-fondé
  mon entreprise Codevia. En parallèle, j’ai lancé mon activité de développeur
  web freelance.
