domain: d9beud.com
url: "https://d9beud.com"
baseurl: ""
title: "Vincent Bathelier"

markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO
locale: fr_FR
twitter:
  username: d9beuD

social:
  github: https://github.com/d9beuD
