domain: d9beud.com
url: "https://d9beud.com"
baseurl: ""
title: "Vincent Bathelier"

markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
locale: fr_FR
twitter:
  username: d9beuD

social:
  github: https://github.com/d9beuD
  linkedin: 
    href: https://www.linkedin.com/in/vincent-bathelier/
    color: "#0077B5"
  malt: 
    href: https://www.malt.fr/profile/vincentbathelier
    color: "#FC5757"
    icon: fa-transporter

description: |
  Après 5 ans d’études à EPSI Montpellier dont 3 en alternance, j’ai co-fondé
  mon entreprise Codevia. En parallèle, j’ai lancé mon activité de développeur
  web freelance.

# Defaults
img_skills_path: /assets/images/skills
img_companies_path: /assets/images/companies
